In [53]:
#biblioteca de manipulação de dados
import pandas as pd

In [54]:
#carregar o banco
banco = pd.read_csv('C:\\Users\\fiago\\OneDrive\\Desktop\\VS Code\\Aulas\\banco de dados.csv', sep=';', encoding='utf-8')

In [55]:

#visualizar o banco
print(banco)

        Nome  Idade Mensalidade  Modalidade
0  Guilherme     19   R$ 150,00  Presencial
1       Iago     21   R$ 200,00  Presencial
2     Felipe     22   R$ 150,00  Presencial
3   Leonardo     23   R$ 300,00         EAD
4    Rodrigo     24   R$ 250,00  Presencial
5    Luciano     25   R$ 400,00         EAD
6      Andre     25   R$ 100,00         EAD
7     Thiago     41     R$ 0,00  Presencial

In [56]:
#mostrar primeiros registros
banco.head(2)

        Nome  Idade Mensalidade  Modalidade
0  Guilherme     19   R$ 150,00  Presencial
1       Iago     21   R$ 200,00  Presencial

In [57]:
#mostrar os dois ultimos registros
banco.tail(2)

     Nome  Idade Mensalidade  Modalidade
6   Andre     25   R$ 100,00         EAD
7  Thiago     41     R$ 0,00  Presencial

In [58]:
#quantas linhas e colunas a tabela tem
print(banco.shape)

(8, 4)

In [59]:
#filtrar registros com nome "Iago"
bancofiltrado = banco[banco["Nome"].str.contains("Iago", case=False ,na=False )]
print(bancofiltrado)

     Nome  Idade Mensalidade  Modalidade
1    Iago     21   R$ 200,00  Presencial
7  Thiago     41     R$ 0,00  Presencial

In [63]:
# trabalhando com campo do tipo inteiro
# fazer conversao para inteiro
banco["Idade"] = banco[ "Idade"].astype(int)
bancofiltrafo = banco[banco["Idade"] > 25]
print(bancofiltrafo)

     Nome  Idade Mensalidade  Modalidade
7  Thiago     41     R$ 0,00  Presencial